## Numerical Python (Numpy)

* Numpy is the fundamental package for scientific computing with Python.
* The main benefit of Numpy is its powerful N-dimensional array object that it provides.
* An array is collection of items stored at contingous memory location.
* The idea is to store items of same type together

In [1]:
import numpy as np

In [3]:
mylist = [1,2,3]
n = np.array(mylist)
print(n)

[1 2 3]


In [4]:
n

array([1, 2, 3])

In [5]:
type(n)

numpy.ndarray

In [6]:
type(mylist)

list

## Numpy Creating Multi-Dimensional Arrays

In [7]:
list_of_lists = np.array([[1,2,3],[4,5,6],[7,8,9]])
list_of_lists

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
list_of_lists.shape

(3, 3)

## Numpy Arange Functions

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,0.75)

array([0.  , 0.75, 1.5 , 2.25, 3.  , 3.75, 4.5 , 5.25, 6.  , 6.75, 7.5 ,
       8.25, 9.  , 9.75])

In [12]:
 np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## Numpy Zeros

In [13]:
zeros = np.zeros(100)

In [14]:
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Numpy Ones

In [19]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Numpy Eye

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.eye(5,5,1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.eye(5,5,-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [26]:
mn = np.arange(0,50)

In [27]:
mn

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [28]:
len(mn)

50

## Numpy Reshape

In [29]:
mn.shape

(50,)

In [30]:
mn.reshape((5,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [31]:
mn.reshape((10,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [34]:
mn

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

## Numpy Linspace

In [32]:
np.linspace(0,50,10)

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

## Numpy Resize

In [33]:
o = np.linspace(0,7,10)
o

array([0.        , 0.77777778, 1.55555556, 2.33333333, 3.11111111,
       3.88888889, 4.66666667, 5.44444444, 6.22222222, 7.        ])

In [35]:
o.reshape(5,2)

array([[0.        , 0.77777778],
       [1.55555556, 2.33333333],
       [3.11111111, 3.88888889],
       [4.66666667, 5.44444444],
       [6.22222222, 7.        ]])

In [36]:
o

array([0.        , 0.77777778, 1.55555556, 2.33333333, 3.11111111,
       3.88888889, 4.66666667, 5.44444444, 6.22222222, 7.        ])

In [37]:
o.resize(5,2)

In [38]:
o

array([[0.        , 0.77777778],
       [1.55555556, 2.33333333],
       [3.11111111, 3.88888889],
       [4.66666667, 5.44444444],
       [6.22222222, 7.        ]])

* The difference between them is that the reshape() does not changes the original array but only returns the changed array, whereas the resize() method returns nothing and directly changes the original array.

## Numpy Generating Random Values with random.rand

In [39]:
np.random.rand(3,2)

array([[0.59429068, 0.39817437],
       [0.71290676, 0.66981724],
       [0.99631085, 0.26476283]])

In [ ]:
# Generate random numbers over a an uniform distribution over [0,1]

## Numpy Generating Random Values with random.randn

In [40]:
 np.random.randn(3,2)

array([[ 1.35468596,  1.73210447],
       [ 0.83236601, -0.66634924],
       [ 1.22956854,  0.01541336]])

In [43]:
# Generate random numbers over a normal distribution

## Numpy Generating Random Values with random.randint

In [4]:
mn = np.random.randint(4,15,10)

In [5]:
mn

array([ 4,  6, 12, 11, 14, 10, 14,  4, 14,  6])

In [2]:
np.random.randint(0,10,(5,3))

array([[1, 0, 0],
       [4, 3, 1],
       [0, 0, 7],
       [5, 6, 5],
       [8, 0, 5]])

## Numpy Indexing and Slicing

In [6]:
mn[1]

6

In [7]:
mn[2:]

array([12, 11, 14, 10, 14,  4, 14,  6])

In [13]:
mm = np.random.randint(0,10,(20,5))

In [17]:
mm[mm>5]

array([7, 8, 6, 8, 9, 8, 9, 9, 9, 7, 8, 7, 8, 7, 7, 9, 8, 7, 9, 8, 9, 9,
       8, 7, 6, 6, 7, 6, 7, 9, 7])

In [20]:
mm > 5

array([[False, False, False, False, False],
       [False, False, False, False,  True],
       [ True, False,  True, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False,  True],
       [False, False,  True,  True,  True],
       [False, False, False, False,  True],
       [False, False, False,  True, False],
       [ True,  True, False,  True,  True],
       [False, False,  True, False, False],
       [False,  True, False, False, False],
       [ True, False, False,  True,  True],
       [ True, False, False, False,  True],
       [False, False, False,  True, False],
       [False, False, False,  True,  True],
       [False,  True, False,  True, False],
       [ True, False,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False,  True]])

## Numpy Broadcasting

In [21]:
mm[mm>5] = 50

In [22]:
mm

array([[ 3,  5,  5,  0,  0],
       [ 1,  0,  5,  0, 50],
       [50,  0, 50,  1,  0],
       [50,  1,  3,  4,  5],
       [50,  2,  3,  5, 50],
       [ 2,  5, 50, 50, 50],
       [ 4,  0,  3,  3, 50],
       [ 5,  3,  1, 50,  5],
       [50, 50,  3, 50, 50],
       [ 4,  2, 50,  1,  3],
       [ 5, 50,  0,  0,  0],
       [50,  5,  5, 50, 50],
       [50,  5,  3,  5, 50],
       [ 4,  4,  5, 50,  2],
       [ 3,  2,  1, 50, 50],
       [ 2, 50,  3, 50,  1],
       [50,  2, 50, 50,  4],
       [ 1,  2,  1,  3,  3],
       [ 5,  5,  3,  3,  0],
       [ 2,  3,  0,  4, 50]])

## Numpy How to Create a copy dataset

In [25]:
copy_of_mm = mm
copy_of_mm # shallow copy

array([[ 3,  5,  5,  0,  0],
       [ 1,  0,  5,  0, 50],
       [50,  0, 50,  1,  0],
       [50,  1,  3,  4,  5],
       [50,  2,  3,  5, 50],
       [ 2,  5, 50, 50, 50],
       [ 4,  0,  3,  3, 50],
       [ 5,  3,  1, 50,  5],
       [50, 50,  3, 50, 50],
       [ 4,  2, 50,  1,  3],
       [ 5, 50,  0,  0,  0],
       [50,  5,  5, 50, 50],
       [50,  5,  3,  5, 50],
       [ 4,  4,  5, 50,  2],
       [ 3,  2,  1, 50, 50],
       [ 2, 50,  3, 50,  1],
       [50,  2, 50, 50,  4],
       [ 1,  2,  1,  3,  3],
       [ 5,  5,  3,  3,  0],
       [ 2,  3,  0,  4, 50]])

In [27]:
another_copy_of_mm = mm.copy()
another_copy_of_mm # deep copy

array([[ 3,  5,  5,  0,  0],
       [ 1,  0,  5,  0, 50],
       [50,  0, 50,  1,  0],
       [50,  1,  3,  4,  5],
       [50,  2,  3,  5, 50],
       [ 2,  5, 50, 50, 50],
       [ 4,  0,  3,  3, 50],
       [ 5,  3,  1, 50,  5],
       [50, 50,  3, 50, 50],
       [ 4,  2, 50,  1,  3],
       [ 5, 50,  0,  0,  0],
       [50,  5,  5, 50, 50],
       [50,  5,  3,  5, 50],
       [ 4,  4,  5, 50,  2],
       [ 3,  2,  1, 50, 50],
       [ 2, 50,  3, 50,  1],
       [50,  2, 50, 50,  4],
       [ 1,  2,  1,  3,  3],
       [ 5,  5,  3,  3,  0],
       [ 2,  3,  0,  4, 50]])

In [30]:
mm[0] = 20

In [33]:
copy_of_mm[0] # shallow copy

array([20, 20, 20, 20, 20])

In [34]:
another_copy_of_mm[0] # deep copy

array([3, 5, 5, 0, 0])

## Numpy Dataframe Introduction

In [35]:
import pandas as pd

In [37]:
data = pd.read_csv('games.csv')
data.head()

id       type                                       name  \
0   12333  boardgame                          Twilight Struggle   
1  120677  boardgame                              Terra Mystica   
2  102794  boardgame                  Caverna: The Cave Farmers   
3   25613  boardgame  Through the Ages: A Story of Civilization   
4    3076  boardgame                                Puerto Rico   

   yearpublished  minplayers  maxplayers  playingtime  minplaytime  \
0         2005.0         2.0         2.0        180.0        180.0   
1         2012.0         2.0         5.0        150.0         60.0   
2         2013.0         1.0         7.0        210.0         30.0   
3         2006.0         2.0         4.0        240.0        240.0   
4         2002.0         2.0         5.0        150.0         90.0   

   maxplaytime  minage  users_rated  average_rating  bayes_average_rating  \
0        180.0    13.0        20113         8.33774               8.22186   
1        150.0    12.0        14383         8.28798               8.14232   
2        210.0    12.0         9262         8.28994               8.06886   
3        240.0    12.0        13294         8.20407               8.05804   
4        150.0    12.0        39883         8.14261               8.04524   

   total_owners  total_traders  total_wanters  total_wishers  total_comments  \
0         26647            372           1219           5865            5347   
1         16519            132           1586           6277            2526   
2         12230             99           1476           5600            1700   
3         14343            362           1084           5075            3378   
4         44362            795            861           5414            9173   

   total_weights  average_weight  
0           2562          3.4785  
1           1423          3.8939  
2            777          3.7761  
3           1642          4.1590  
4           5213          3.2943

In [39]:
duplicate_dateset = data.copy()

In [40]:
duplicate_dateset

id                type  \
0       12333           boardgame   
1      120677           boardgame   
2      102794           boardgame   
3       25613           boardgame   
4        3076           boardgame   
...       ...                 ...   
81307  184441  boardgameexpansion   
81308  184442           boardgame   
81309  184443           boardgame   
81310  184449           boardgame   
81311  184451           boardgame   

                                                    name  yearpublished  \
0                                      Twilight Struggle         2005.0   
1                                          Terra Mystica         2012.0   
2                              Caverna: The Cave Farmers         2013.0   
3              Through the Ages: A Story of Civilization         2006.0   
4                                            Puerto Rico         2002.0   
...                                                  ...            ...   
81307                               Micro Rome: Aegyptus         2015.0   
81308  Trivial Pursuit: Marvel Cinematic Universe  Da...         2013.0   
81309                                          BEARanoia         2015.0   
81310                                            Freight         2015.0   
81311                                  Bingo Animal Kids         2010.0   

       minplayers  maxplayers  playingtime  minplaytime  maxplaytime  minage  \
0             2.0         2.0        180.0        180.0        180.0    13.0   
1             2.0         5.0        150.0         60.0        150.0    12.0   
2             1.0         7.0        210.0         30.0        210.0    12.0   
3             2.0         4.0        240.0        240.0        240.0    12.0   
4             2.0         5.0        150.0         90.0        150.0    12.0   
...           ...         ...          ...          ...          ...     ...   
81307         1.0         1.0          0.0         30.0          0.0    10.0   
81308         2.0         0.0          0.0          0.0          0.0    12.0   
81309         2.0        15.0          1.0          1.0          1.0     0.0   
81310         2.0         4.0         60.0         30.0         60.0     8.0   
81311         1.0         6.0         10.0         10.0         10.0     2.0   

       users_rated  average_rating  bayes_average_rating  total_owners  \
0            20113         8.33774               8.22186         26647   
1            14383         8.28798               8.14232         16519   
2             9262         8.28994               8.06886         12230   
3            13294         8.20407               8.05804         14343   
4            39883         8.14261               8.04524         44362   
...            ...             ...                   ...           ...   
81307            0         0.00000               0.00000             0   
81308            0         0.00000               0.00000             0   
81309            0         0.00000               0.00000             0   
81310            0         0.00000               0.00000             0   
81311            0         0.00000               0.00000             0   

       total_traders  total_wanters  total_wishers  total_comments  \
0                372           1219           5865            5347   
1                132           1586           6277            2526   
2                 99           1476           5600            1700   
3                362           1084           5075            3378   
4                795            861           5414            9173   
...              ...            ...            ...             ...   
81307              0              0              0               0   
81308              0              0              0               0   
81309              0              0              0               0   
81310              0              0              0               0   
81311              0              0          